cms/urls.py
from django.conf.urls import url
from cms import views

urlpatterns = [
    # schedule
    url(r'^schedule/$', views.schedule_list, name='schedule_list'),   # list of schedule
    url(r'^schedule/add/$', views.schedule_edit, name='schedule_add'),  # add new schedule
    url(r'^schedule/mod/(?P<schedule_id>\d+)/$', views.schedule_edit, name='schedule_mod'),  # modify schedule
    url(r'^schedule/del/(?P<schedule_id>\d+)/$', views.schedule_del, name='schedule_del'),   # delete schedule
    url(r'^discussion/(?P<schedule_id>\d+)/$', views.DiscussionList.as_view(), name='discussion_list'),  #list of discussion
    url(r'^discussion/add/(?P<schedule_id>\d+)/$', views.discussion_edit, name='discussion_add'),        # add discussion
    url(r'^discussion/mod/(?P<schedule_id>\d+)/(?P<discussion_id>\d+)/$', views.discussion_edit, name='discussion_mod'), # modify discussion
    url(r'^discussion/del/(?P<schedule_id>\d+)/(?P<discussion_id>\d+)/$', views.discussion_del, name='discussion_del'), # delete discussion
]

scheduleManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include('cms.urls', namespace='cms')),
]

cms/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    EventName = models.CharField(max_length=20)
    Date = models.IntegerField()
    Place = models.CharField(max_length=20)
    Note = models.CharField(max_length=40)



class Discussion(models.Model):
    schedule = models.ForeignKey(Schedule, verbose_name='Schedule', related_name='discussions')
    discussion = models.TextField('Discussion', blank=True)

    def __str__(self):
        return self.discussion

cms/forms.py
from django.forms import ModelForm
from cms.models import Schedule, Discussion


class ScheduleForm(ModelForm):
    # Form of schedule
    class Meta:
        model = Schedule
        fields = ('EventName', 'Date', 'Place', 'Note',)


class DiscussionForm(ModelForm):
    class Meta:
        model = Discussion
        fields = ('discussion', )

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from cms.models import Schedule, Discussion
from cms.forms import ScheduleForm, DiscussionForm
from django.views.generic.list import ListView


def schedule_list(request):
    # list of schedule
    schedules = Schedule.objects.all().order_by('id')
    return render(request,
                  'cms/schedule_list.html',  # html template
                  {'schedules': schedules})  # data which will be sent to template


def schedule_edit(request, schedule_id=None):
    # edit schedule
    if schedule_id:  # schedule_id is defined(modified)
        schedule = get_object_or_404(Schedule, pk=schedule_id)
    else:  # schedule_id is not defines(added)
        schedule = Schedule()

    if request.method == 'POST':
        form = ScheduleForm(request.POST, instance=schedule)  # make a form from POST request data.
        if form.is_valid():  # check if it is valid
            schedule = form.save(commit=False)
            schedule.save()
            return redirect('cms:schedule_list')
    elif request.method == "GET":
        form = ScheduleForm(instance=schedule)  # make a form from schedule instance

    return render(request, 'cms/schedule_edit.html', dict(form=form, schedule_id=schedule_id))


def schedule_del(request, schedule_id):
    schedule = get_object_or_404(Schedule, pk=schedule_id)
    schedule.delete()
    return redirect('cms:schedule_list')


class DiscussionList(ListView):
    context_object_name = 'discussions'
    template_name = 'cms/discussion_list.html'
    paginate_by = 5  # max paging = 5

    def get(self, request, *args, **kwargs):
        schedule = get_object_or_404(Schedule, pk=kwargs['schedule_id'])  # read schedule as parent
        discussions = schedule.discussions.all().order_by('id')  # read discussion as child
        self.object_list = discussions

        context = self.get_context_data(object_list=self.object_list, schedule=schedule)
        return self.render_to_response(context)


def discussion_del(request, schedule_id, discussion_id):
    discussion = get_object_or_404(Discussion, pk=discussion_id)
    discussion.delete()
    return redirect('cms:discussion_list', schedule_id=schedule_id)


def discussion_edit(request, schedule_id, discussion_id=None):
    schedule = get_object_or_404(Schedule, pk=schedule_id)  # read schedule as a parent
    if discussion_id:  # discussion_id is defined (modify)
        discussion = get_object_or_404(Discussion, pk=discussion_id)
    else:  # discussion_id is not defined (adding)
        discussion = Discussion()

    if request.method == 'POST':
        form = DiscussionForm(request.POST, instance=discussion)  # make a form from request data
        if form.is_valid():  # check if it is valid
            discussion = form.save(commit=False)
            discussion.schedule = schedule  # set schedule as parent
            discussion.save()
            return redirect('cms:discussion_list', schedule_id=schedule_id)
    else:  # GET
        form = DiscussionForm(instance=discussion)  # make a form from discussion instance

    return render(request,
                  'cms/discussion_edit.html',
                  dict(form=form, schedule_id=schedule_id, discussion_id=discussion_id))

cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">

<head>
<meta charset="UTF-8">
<title>{% block title %}My books{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'  type='text/css'>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<style>
    h3{
    font-family: 'Lobster', cursive;
    font-size: 50px;
}
    h4{
    font-family: 'Open Sans Extra-Bold', sans-serif;
    font-size: 20px;
    font-weight: 800;
}
    body{
        background: linear-gradient(to right, #be93c5, #7bc6cc);

    }
    table {
    background-color: #dfe3e6;
    font-family: 'Open Sans', sans-serif;
}
</style>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

cms/templates/cms/discussion_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}Edit Discussion{% endblock title %}

{% block content %}
    <h3 class="page-header">Sched!</h3>
    <h4>Edit Discussion</h4>
    {% if discussion_id %}
    <form action="{% url 'cms:discussion_mod' schedule_id=schedule_id discussion_id=discussion_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:discussion_add' schedule_id=schedule_id %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Send</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:discussion_list' schedule_id=schedule_id %}" class="btn btn-default btn-sm">Back</a>
{% endblock content %}

cms/templates/cms/discussion_list.html
{% extends "base.html" %}

{% block title %}Discussions{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">Sched!</h3>
    <h4>Discussions <small>{{ schedule.EventName }}</small></h4>
    <a href="{% url 'cms:discussion_add' schedule_id=schedule.id %}" class="btn btn-default btn-sm">Add</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>discussion</th>
          <th>control</th>
        </tr>
      </thead>
      <tbody>
        {% for discussion in discussions %}
        <tr>
          <td>{{ discussion.id }}</td>
          <td>{{ discussion.discussion|linebreaksbr }}</td>
          <td>
            <a href="{% url 'cms:discussion_mod' schedule_id=schedule.id discussion_id=discussion.id %}" class="btn btn-default btn-sm">Modify</a></a>
            <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ discussion.id }}" url="{% url 'cms:discussion_del' schedule_id=schedule.id discussion_id=discussion.id %}">Delete</button></button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

    <div>
      <a href="{% url 'cms:schedule_list' %}" class="btn btn-default btn-sm">back</a>
    </div>

{# dialog to confirm delete #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">confirm</h4>
      </div>
      <div class="modal-body">
        <p>Do you really delete</p><p>ID: <span id="del_pk"></span></p><p>?</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

cms/templates/cms/schedule_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}Edit_Schedule{% endblock title %}

{% block content %}
    <h3 class="page-header">Sched!</h3>
    <h4>Edit Schedule</h4>
    {% if schedule_id %}
    <form action="{% url 'cms:schedule_mod' schedule_id=schedule_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:schedule_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
    {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Send</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:schedule_list' %}" class="btn btn-default btn-sm">Back</a>
{% endblock content %}

cms/templates/cms/schedule_list.html
{% extends "base.html" %}
{% block title %}List_of_Schedules{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
  margin-top: 8px;
    background-color: #dfe3e6;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">Sched!</h3>
    <h4>List of Schedules</h4>
    <a href="{% url 'cms:schedule_add' %}" class="btn btn-default btn-sm">Add</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Event Name</th>
          <th>Date</th>
          <th>Place</th>
          <th>Note</th>
          <th>Control</th>
        </tr>
      </thead>
      <tbody>
        {% for schedule in schedules %}
        <tr>
          <td>{{ schedule.id }}</td>
          <td>{{ schedule.EventName }}</td>
          <td>{{ schedule.Date }}</td>
          <td>{{ schedule.Place }}</td>
          <td>{{ schedule.Note }}</td>

          <td>
            <a href="{% url 'cms:schedule_mod' schedule_id=schedule.id %}" class="btn btn-default btn-sm">Modify</a>
            <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ schedule.id }}" url="{% url 'cms:schedule_del' schedule_id=schedule.id  %}">Delete</button></button>
            <a href="{% url 'cms:discussion_list' schedule_id=schedule.id %}" class="btn btn-default btn-sm btn-primary">List of Discussion</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">confirm</h4>
      </div>
      <div class="modal-body">
        <p>Do you really delete</p><p>ID: <span id="del_pk"></span></p><p>?</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}